#!/bin/bash

set -e
set -x

# Set var with your database name
DBNAME="MN908947.3"

#erase filesystem effects of any previous failed attempts
rm -rfv $CONDA_PREFIX/share/snpeff-5.4.0a-0/data/$DBNAME

mkdir -pv $CONDA_PREFIX/share/snpeff-5.4.0a-0/data/$DBNAME

# wget gzipped gtf from http://ftp.ensemblgenomes.org/pub/viruses/gtf/sars_cov_2/Sars_cov_2.ASM985889v3.101.gtf.gz
# UNZIP GTF, keeping .gz version
gunzip -kvf Sars_cov_2.ASM985889v3.101.gtf.gz

REFFASTA=artic-ncov2019/primer_schemes/nCoV-2019/V4.1/SARS-CoV-2.reference.fasta
GTF=Sars_cov_2.ASM985889v3.101.gtf

cp -v $GTF $CONDA_PREFIX/share/snpeff-5.4.0a-0/data/$DBNAME/genes.gtf
cp -v $REFFASTA $CONDA_PREFIX/share/snpeff-5.4.0a-0/data/$DBNAME/sequences.fa

# MN908947.3 is already in config

#Build the database
snpEff build -gtf22 -noCheckCds -noCheckProtein -v $DBNAME